### ISSUE TITLE
per-pkg Q&A tab: show only titles of ROS Answers questions?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/rosindex#197]
Currently the tab shows the complete question, which is nice, but for packages with 'long' first posts, it also means that the Q&A tab renders a really long page.

An example would be the [fanuc page](https://index.ros.org/p/fanuc/github-ros-industrial-fanuc/#melodic-questions). I believe the tab does not show all 24 posts (and there are packages with far more questions listed), but it's already quite long.

Would it perhaps be an idea to list clickable links with just the titles instead?

As the answers are on ROS Answers in any case (and require a click and page load to see), just showing the titles might provide a clearer overview of available Q&As.

**Comment by gavanderhoorn** [comment]
And just to be clear: we can submit a PR for this, but I wanted to get some opinions first.

**Comment by tfoote** [comment]
Something to show the list better would be nice. 

We have the truncated content on robots.ros.org: https://robots.ros.org/turtlebot/ which gives you a little bit more context than just the title. 

Potentially an expandable box with a small preview of the content would be a good compromise. It would also be great to have the same behavior on both sites.

**Comment by max-krichenbauer** [comment]
@tfoote I implemented your suggestion as https://github.com/ros-infrastructure/rosindex/pull/201
I hope I understood it correctly. Please let me know if you would like changes.

**Comment by max-krichenbauer** [comment]
I guess this issue can be closed now, since the PR implementing it has been merged.

**Comment by gavanderhoorn** [comment]
Indeed.

I'm still not sure whether the metapackage should actually show all of the tags, but for now this is OK.

thanks for the work @max-krichenbauer :+1:

**Comment by gavanderhoorn** [comment]
Indeed. Thanks for the work @max-krichenbauer :+1:
